spring:
    datasource:
      url: jdbc:mysql://localhost:3306/libros_recordatorio?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
      username: root
      password: root1234
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    thymeleaf:
        cache: false
    servlet: 
        multipart.max-file-size = 5MB
        multipart.max-request-size=10MB
    mail: 
      host=smtp.gmail.com
      port=587
      username=proyectoegg159@gmail.com
      password=enviarmail123
      properties.mail.smtp.auth=true
      properties.mail.smtp.starttls.enable=true
